version: '3.9'

services:
  client-backend:
    image: news:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - service-db
    links:
      - redis
    environment:
      DATABASE_URL: jdbc:postgresql://service-db:5433/postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres

  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5433"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  db-data: