spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://service-db:5432/postgres
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

cache:
  size: 5
  algorithm: lru