spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234Qwer
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath*:classpath*:database/initDB.sql
#      data-locations: classpath*:classpath*:database/populateDB.sql